server:
  port: 8080
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: core
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/GD
    username: root
    password: 12345
  mail:
    host: smtp.gmail.com
    port: 587
    username: gunho3987@gmail.com
    password: difa evrt cbmv sqdg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      password:
      port: 6379
      timeout: 60000
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms


jwt:
  secret: mysecretkeythisisveryimportantandshouldbemuchmorelonger
  expiration: 86400 # 24??


logging:
  level:
    root: INFO
    dev.gunho: INFO
  file:
    name: /Users/gang-geonho/Develope/portfolio/core/logs/app.log
